trigger:
- master
- az-devops

pool:
  vmImage: windows-2019

steps:
- powershell: |
    choco install docfx -y
    docfx docfx.json
    if ($lastexitcode -ne 0){
      throw ("Error generating document")
    }
  displayName: "docfx build"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: _site
    artifactName: site

- powershell: |
    git clone https://github.com/docascode/docfx-seed.git -b gh-pages _origin_site -q
    Remove-Item _origin_site/* -Exclude _origin_site/.git -Recurse
    ls _site
    Copy-Item _site/* _origin_site -Recurse -Force
    Set-Location _origin_site
    git config --global use.email "renzeyu@microsoft.com"
    git config --global use.name "Renze Yu"
    git config core.safecrlf false # disable LF/CRLF check to avoid break Azure Pipelines
    git add -A 2>$1
    echo "log before commit"
    git commit -m "Update documents" -q 2>$1 | %{ "$_" }
    echo "log after commit"
    exec "git -c http.extraheader='AUTHORIZATION: basic $env:BASIC_AUTH_TOKEN' push origin gh-pages -q 2>$1"
  displayName: "docfx publish"
  env:
    BASIC_AUTH_TOKEN: $(BASIC_AUTH_TOKEN)