trigger:
- master
- az-devops

pool:
  vmImage: windows-2019

steps:
- powershell: |
    choco install docfx -y
    docfx docfx.json -o _site
    if ($lastexitcode -ne 0){
      throw ("Error generating document")
    }
  displayName: "docfx build"
- powershell: |
    git clone https://github.com/docascode/docfx-seed.git -b gh-pages _origin_site -q
    Remove-Item _origin_site/* -Exclude _origin_site/.git -Recurse
    Copy-Item _site _origin_site -Recurse -Force
    Set-Location _origin_site
    git add .
    git commit -m "Update documents" -q
    git -c http.extraheader="AUTHORIZATION: bearer $env:SYSTEM_ACCESSTOKEN" push origin gh-pages -q
  displayName: "docfx publish"
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)